# Generated by Django 5.2.9 on 2025-12-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_funcionalidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorizacao',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bairro',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coleta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empresaterc',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empresaterccoleta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='funcionariocoleta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='licenca',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='logradouro',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orgaoambiental',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orgaoambientallicenca',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='residuo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='telefone',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='veiculocoletafuncionario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='veiculoresiduo',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='solicitacoleta',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='solicitacoleta',
            name='tipagem_residuo',
        ),
    ]
