# Generated by Django 5.2.9 on 2025-12-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_funcionalidades', '0002_alter_autorizacao_options_alter_bairro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoleta',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacoleta',
            name='tipagem_residuo',
            field=models.CharField(choices=[('L', 'Liquido'), ('G', 'Gasoso'), ('S', 'Sólido')], default='S', max_length=1),
        ),
    ]
